### ISSUE TITLE
auth:setup doesnt have a desc msg

### ISSUE THREAD

**Issue by ctf0** [adonisjs/adonis-commands#10]
![screen shot 2016-11-25 at 10 52 38 pm](https://cloud.githubusercontent.com/assets/7388088/20635159/003e2e4a-b362-11e6-8a83-1ff41e7c9dcd.jpg)

**Comment by RomainLanz** [comment]
Could you create a PR?

**Comment by ctf0** [comment]
sure but the issue is that the cmnd already have the desc but for some reason its not showing up in the trmnl

**Comment by ctf0** [comment]
sweet
