### ISSUE TITLE
limit files to javascript files when running migrations

### ISSUE THREAD

**Issue by seanc** [adonisjs/adonis-commands#20]
i'm currently using a submodule for my migrations folder which requires me to keep some extra files there, however since adonis tries to parse all files it ends up with a synax error, would it be possible to limit the files to just javascript types?

**Comment by seanc** [comment]
or perhaps ignore hidden files.

**Comment by thetutlage** [comment]
Yup on the way of doing same

**Comment by thetutlage** [comment]
Fixed in https://github.com/adonisjs/adonis-lucid/commit/a21d6fca04e09a664057d165977af50dd6757be6
