### ISSUE TITLE
./ace make:migration -c fails

### ISSUE THREAD

**Issue by tremendus** [adonisjs/adonis-commands#5]
```
#develop branch
./ace make:migration -c accounts 
// fails with error missing required argument name, same with --create 
```

**Comment by thetutlage** [comment]
Yes you have to name the migration file

`./ace make:migration accounts -c accounts

**Comment by tremendus** [comment]
Ooooohhhhh! I see. Name the table, then the file. Sorry! I didn't get that from the --help. Now I do :)
