### ISSUE TITLE
How to test the new created commands?

### ISSUE THREAD

**Issue by allanfreitas** [adonisjs/adonis-commands#7]
I'm trying to port my custom route:list command 
that I've created on app/Commands/RouteList.js
and when I've tried to put a "ln -s" on the node_modules of an "adonis-app" 
to my adonis-commands clone repo to test, this error popups :(

![adonis-commands-error-0198303812098](https://cloud.githubusercontent.com/assets/304086/18227681/53814c54-7203-11e6-9164-65ab0c00cf41.png)

**I've just cloned don't have made any changes yet**

**Comment by thetutlage** [comment]
Do you have `adonis-fold` installed on the host app?

**Comment by allanfreitas** [comment]
Yes, I've created a this _cmdhelper_ project with `adonis new cmdhelper`.
And all ./ace commands just works.
After I've made a symbolic link for my github adonis-command clone it should work, but it don't :(

**Comment by thetutlage** [comment]
Can u please share the `package.json` file of your `adonis-commands` repo and I will suggest to do `npm install` after the symbolic link.

**Comment by allanfreitas** [comment]
After do a npm install on the cmdhelper(main app), the error: 
`Error: Cannot find module 'adonis-fold'` appears.
And I've already tried to run a npm install after that, 
on the adonis-commands path, them the error changes to: 
`Error: Cannot find module 'Helpers'`

My adonis-commands package.json:
https://gist.github.com/allanfreitas/359d55a57bc460a37abfe11a3d5c2fb9

**Comment by allanfreitas** [comment]
If you can/want answer, I want to know: 
what's your process when developing the additional packages not on adonis-framework?

**Comment by allanfreitas** [comment]
This could help next contributors to AdonisJS :)

**Comment by thetutlage** [comment]
Installing `adonis-fold` within your package will not work, since the IoC container will be different for the app and your module.

I will look into the symbolic link issue. The best for now I can suggest is to `npm install` the local module by giving the directory path.

It will be of little pain that you have to reinstall the package after the changes but is the only option until I know the real issue with the symbolic link thing.

**Comment by thetutlage** [comment]
> what's your process when developing the additional packages not on adonis-framework

Not sure what you mean?

**Comment by thetutlage** [comment]
Also how do you create the symlink?

**Comment by allanfreitas** [comment]
do you use that npm install local module during the develop?

**Comment by allanfreitas** [comment]
the symlink command:
`ln -s ~/projetos/forks/adonis-commands/ node_modules/adonis-commands`

**Comment by thetutlage** [comment]
Ohhh I would suggest to use `npm link` command https://docs.npmjs.com/cli/link

**Comment by allanfreitas** [comment]
Ohh, thanks, I will try it

**Comment by allanfreitas** [comment]
npm link does not solved my issue :(

**Comment by obstschale** [comment]
I ran into the same problem. I created a adonis package with custom provider. I used `npm link` like described [here](https://docs.npmjs.com/cli/link) and had the same Error `Error: Cannot find module 'Helpers'`

Installing the package locally with `npm install ~/path/to/package` solved the problem, but using symlinks would be better. I hope you find the problem.

**Comment by thetutlage** [comment]
Running nodejs with `--preserve-symlinks` flag fixes the issue.

```bash
node --preserve-symlinks server.js
```

**Comment by webdevian** [comment]
Just to add for anyone else that gets stuck with this for building packages with ace commands, the same flag can be used

```
node --preserve-symlinks ace
```
